[fish.files]
fish = "~/.config/fish/config.fish"

[tmux.files]
tmux = "~/.tmux.conf"

[starship.files]
starship = "~/.config/starship.toml"

# Waybar config stolen from https://github.com/n0tsteve/glorious-dots
[waybar.files]
"waybar/config" = "~/.config/waybar/config"
"waybar/style" = "~/.config/waybar/style.css"


[sway]
depends = ["waybar"]

[sway.files]
"sway/config" = "~/.config/sway/config"
