[fish.files]
fish = "~/.config/fish/config.fish"

[tmux.files]
tmux = "~/.tmux.conf"

[starship.files]
starship = "~/.config/starship.toml"

[wallpapers.files]
"wallpapers/w1.jpg" = "~/.config/wallpapers/w1.jpg"

# Waybar config stolen from https://github.com/n0tsteve/glorious-dots
[waybar.files]
"waybar/config" = "~/.config/waybar/config"
"waybar/style" = "~/.config/waybar/style.css"


[sway]
depends = ["waybar", "wallpapers"]

[sway.files]
"sway/config" = "~/.config/sway/config"
