[aux.files]
"aux/getmedia" = "~/.aux/getmedia.py"
"aux/rofipower" = "~/.aux/rofipower.sh"
"aux/swaylock" = "~/.aux/swaylock.sh"
"aux/sshipleiria" = "~/.aux/sshipleiria"

[fish.files]
fish = "~/.config/fish/config.fish"

[tmux.files]
tmux = "~/.tmux.conf"

[starship.files]
starship = "~/.config/starship.toml"

[alacritty.files]
alacritty = "~/.config/alacritty/alacritty.yml"

[wallpapers.files]
"wallpapers/w1.jpg" = "~/.config/wallpapers/w1.jpg"

# Waybar config stolen from https://github.com/n0tsteve/glorious-dots
[waybar.files]
"waybar/config" = "~/.config/waybar/config"
"waybar/style" = "~/.config/waybar/style.css"


[sway]
depends = ["aux", "waybar", "wallpapers"]

[sway.files]
"sway/config" = "~/.config/sway/config"
